"""Imag1

Revision ID: 02988f6ff674
Revises: 19bf5b1393ef
Create Date: 2022-06-09 16:12:59.698848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02988f6ff674'
down_revision = '19bf5b1393ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
