"""Image

Revision ID: 19bf5b1393ef
Revises: e752f02aec47
Create Date: 2022-06-09 14:40:09.469391

"""
from tokenize import String
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19bf5b1393ef'
down_revision = 'e752f02aec47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('profile_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'profile_url')
    # ### end Alembic commands ###
