"""Category

Revision ID: 1d13276036a5
Revises: 7d5a99566ab1
Create Date: 2022-05-31 17:45:54.052536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d13276036a5'
down_revision = '7d5a99566ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Category_id'), 'Category', ['id'], unique=False)
    op.create_table('ReviewQuestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ReviewQuestion_id'), 'ReviewQuestion', ['id'], unique=False)
    op.drop_index('ix_Teacher_id', table_name='Teacher')
    op.drop_table('Teacher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teacher',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Teacher_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('stream', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Teacher_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Teacher_pkey')
    )
    op.create_index('ix_Teacher_id', 'Teacher', ['id'], unique=False)
    op.drop_index(op.f('ix_ReviewQuestion_id'), table_name='ReviewQuestion')
    op.drop_table('ReviewQuestion')
    op.drop_index(op.f('ix_Category_id'), table_name='Category')
    op.drop_table('Category')
    # ### end Alembic commands ###
