"""BlackListToken

Revision ID: 2f9adb51e63b
Revises: 1d13276036a5
Create Date: 2022-06-02 14:56:11.021511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9adb51e63b'
down_revision = '1d13276036a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BlackListToken', sa.Column('access_token', sa.String(), nullable=False))
    op.add_column('BlackListToken', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('BlackListToken', sa.Column('expire', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BlackListToken', 'expire')
    op.drop_column('BlackListToken', 'created_at')
    op.drop_column('BlackListToken', 'access_token')
    # ### end Alembic commands ###
