"""Imag1

Revision ID: 3902c707d666
Revises: 02988f6ff674
Create Date: 2022-06-09 16:14:10.463025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3902c707d666'
down_revision = '02988f6ff674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
