"""BlackListToken1

Revision ID: 575d04a644a2
Revises: 2f9adb51e63b
Create Date: 2022-06-02 17:05:24.178106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '575d04a644a2'
down_revision = '2f9adb51e63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BlackListToken', 'expire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BlackListToken', sa.Column('expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
