"""Add teachssssssssser

Revision ID: 7d5a99566ab1
Revises: 424f489c965e
Create Date: 2022-05-31 14:07:25.981548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5a99566ab1'
down_revision = '424f489c965e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
