"""google

Revision ID: bfec8b80233f
Revises: 575d04a644a2
Create Date: 2022-06-07 17:10:14.556511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfec8b80233f'
down_revision = '575d04a644a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('provider', sa.String(), nullable=True))
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('User', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('User', 'provider')
    # ### end Alembic commands ###
