"""Add teachssser

Revision ID: d7cbc03f67b0
Revises: c610a957f50c
Create Date: 2022-05-31 11:36:18.062997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cbc03f67b0'
down_revision = 'c610a957f50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
